import { existsSync, writeFileSync } from 'node:fs';
const faces=[
  ['Gilroy-Regular.woff2',400,'normal'],['Gilroy-Medium.woff2',500,'normal'],
  ['Gilroy-SemiBold.woff2',600,'normal'],['Gilroy-Heavy.woff2',900,'normal'],
  ['Gilroy-SemiBoldItalic.woff2',600,'italic']
];
const available=faces.filter(([file])=>existsSync('public/fonts/'+file));
const css=available.map(([file,weight,style])=>
  "@font-face{font-family:'Gilroy';font-weight:"+weight+";font-style:"+style+";font-display:swap;src:url('/fonts/"+file+"') format('woff2')}").join('\n');
writeFileSync('src/fonts.generated.css','/* Generated by prepare-fonts.mjs. See README for missing licensed Gilroy fonts. */\n'+css+'\n');
if(available.length!==faces.length)console.info('Gilroy: '+available.length+'/5 local faces. Documented development fallback is active for missing faces.');
